config/routes.rb
Rails.application.routes.draw do
  resources :editusers, only: [:edit ,:update], param: :UserID


# ユーザ編集
  get '/editusers/:UserID', to: 'local/users#edit'
  get '/update/:UserID', to: 'local/users#update'
  patch '/update/:UserID', to: 'local/users#update'
  put '/update/:UserID', to: 'local/users#update'

# ユーザ作成
  get '/signup', to: 'local/users#new'

# サインイン 
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

# サインアウト
  delete '/signout', to: 'sessions#destroy'

  # local_users_path localがつく
  namespace :local do
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
# bcryptをインストールして使用できるようになる　
    has_secure_password

    # 不完全なデータを排除する
    # presence 入力させるかどうか, uniquness:keyかどうか
    validates :UserID, presence: true, uniqueness: true
    validates :UserName, presence: true
    validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # CSRF有効
    protect_from_forgery with: :exception
    # CSRF無効
    #protect_from_forgery with: :null_session

    # ヘルパー　current_userを使用可能にする
    helper_method :current_user

    # サインインしているか調べる
    before_action :signin_required
    

    private

    def current_user
        # セッションの情報を格納する
        @current_user ||= User.find_by(UserID: session[:UserID]) if session[:UserID]
        
    end

    def signin_required
        redirect_to signin_path unless current_user
    end

end

app/controllers/local/users_controller.rb
class Local::UsersController < ApplicationController
  # CSRF対策からcreateアクションを除外
  protect_from_forgery except: :create
  # singin_requiredをスキップする
  skip_before_action :signin_required, only: [:new, :create]


  # usersテーブルに登録する（サインアップ画面）
  def new
    # Userモデルを使用してuserインスタンスを作成する
    @user = User.new
  end

  # /userがpostされたらユーザを作成する
  def create
    # HTMLから受けとったパラメータをuser_paramsに送る
    @user = User.new(user_params)

    # 入力したパスワードが一致しなかった場合
    if @user.password != @user.password_confirmation
      flash.now[:notice] = "パスワードが一致しません"
      render :new

    # 入力したUserIDがすでに使われている場合
    elsif User.where(UserID: @user.UserID).present? then
      flash.now[:notice] = "「#{@user.UserID}」はすでに使われています"
      render :new

    # 入力項目が正しい場合
    else
      # userインスタンスを登録
      @user.save!
      flash.now[:notice] = "ユーザ「#{@user.UserID}」を登録しました。"
      redirect_to local_user_path(@user.UserID)
    end
  end

  def index
  end

  # 編集用の画面
  def edit
    @user = User.find_by(UserID: current_user.UserID)
  end

  # ユーザの更新処理
  def update
    # サインインしているユーザのUserIDを検索する
    user = User.find_by(UserID: current_user.UserID)
    # フォームからパラメータを受け取り更新する
    user.update(useredit_params)
    redirect_to local_users_path
    
    @user = User.find_by(UserID: params[:UserID])
  end
    

  def show
    # 受け取ったUserIDを検索する
    @user = User.find_by(UserID: params[:UserID])
  end



  # privateの下からは private action
  private

  # userインスタンスのパラメータ（column）を指定する
  def user_params
    # 受け取ったパラメータをcolumnに追加する
    params.require(:user).permit(:UserID, :UserName, :password, :password_confirmation)
  end

  def useredit_params
    # 受け取ったパラメータをcolumnに追加する
    params.require(:user).permit(current_user.UserID, :UserName)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # CSRF対策からcreateアクションを除外
  protect_from_forgery except: :create 
  # singin_requiredをスキップする
  skip_before_action :signin_required

  def new
  end

  def create

    # userオブジェクトにUserIDを格納する
    user = User.find_by(UserID: session_params[:UserID])

    # パスワード認証が一致していたら
    if user&.authenticate(session_params[:password])
      session[:UserID] = user.UserID
      redirect_to local_users_path, notice: 'サインインしました'
    else
      render :new
    end

  end

  def destroy
    # セッションを削除する
    reset_session
    redirect_to local_users_path, notice: 'サインアウトしました。'
  end

  # privateの下からは private action
  private

  def session_params
    params.require(:session).permit(:UserID, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/local/users_helper.rb
module Local::UsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ログイン状態 -->
    <% if current_user %>
      <div class="outer">
        <div class="inner">
          <div class="logo-wrapper"><%= image_tag '/logotype.png', :size =>"150x50" %></div>
          <nav>
            <ul id="list">
              <li class="list-items">
                <%= link_to "プロフィール編集", edituser_path(session[:UserID]), method: :get %>
              </li>
              <li class="list-items">
                <%= link_to "サインアウト", signout_path(session[:UserID]), method: :delete %>
              </li>
            </ul>
          </nav>
        </div>
      </div>

    <!-- ログインしていない状態 -->
    <% else %>
      <div class="outer">
        <div class="inner">
          <div class="logo-wrapper"><%= image_tag '/logotype.png', :size =>"150x50" %></div>
          <nav>
            <ul id="list">
              <li class="list-items">
                <%= link_to("ログイン", "/signin") %>
              </li>
              <li class="list-items">
                <%= link_to("新規登録", "/signup") %>
              </li>
            </ul>
          </nav>
        </div>
      </div> 
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/local/users/edit.html.erb
<div class="wrapper">
    <h1>ユーザ編集</h1>

    <!-- postメソッドを使用するフォームを作成する -->
    <form action="/update/:UserID" method="patch">
        <!-- ユーザIDの表示欄 -->
        <p>
            <label for="userid">
                ユーザID
            </label>
            <input class="form-control" id="user_id" type="text" name="user[UserID]" readonly="readonly" value=<%= current_user.UserID%> required>
        </p>
    <form action="/local/users" method="post">

        <!-- ユーザ名の入力欄 -->
        <p>
            <label for="username">
                ユーザ名
            </label>
            <input class="form-control" id="user_name" type="text" name="user[UserName]" required>
        </p>

        <p>
            <input type="submit" name="update" value="変更する" class="updatebtn" data-disable-with="変更する">
        </p>
    </form>
</div>

app/views/local/users/index.html.erb
<div class="wrapper">
    <!-- <div class="flash-notice">
        <%= session[:UserID] %> が <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div> -->

    <h1>ユーザトップページ</h1>
</div>

app/views/local/users/new.html.erb
<!-- <% if flash[:notice] %>
    <div class="flash-notice">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %> -->
<div class="wrapper">
    <h1>サインアップ</h1>

    <!-- postメソッドを使用するフォームを作成する -->
    <form action="/local/users" method="post">
        <!-- ユーザIDの入力欄 -->
        <p>
            <label for="userid">
                ユーザID
            </label>
            <input class="form-control" id="user_id" type="text" name="user[UserID]" required>
        </p>

        <!-- ユーザ名の入力欄 -->
        <p>
            <label for="username">
                ユーザ名
            </label>
            <input class="form-control" id="user_name" type="text" name="user[UserName]" required>
        </p>

        <!-- ユーザパスワードの入力欄 -->
        <p>
            <label for="password">
                パスワード
            </label>
            <input class="form-control" id="user_password" type="password" name="user[password]" required>
        </p>

        <!-- ユーザパスワード確認の入力欄 -->
        <p>
            <label for="passwordconfirmation">
                パスワード確認
            </label>
            <input class="form-control" id="user_password_confirmation" type="password" name="user[password_confirmation]" required>
        </p>

        <p>
            <input type="submit" name="commit" value="登録する" class="createbtn" data-disable-with="登録する">
        </p>
    </form>
</div>

app/views/local/users/show.html.erb
<% if flash[:notice] %>
  <div class="flash-notice">
        <%= flash[:notice] %>
        <!-- 特殊文字のボタン -->
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>
<h1>プロフィール</h1>
<p>Find me in app/views/local/users/show.html.erb</p>